// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwwQbUH0KJUGscVKRSmXJCpguuZSbA0w',
    appId: '1:274767761536:web:820135382f7689d9e45665',
    messagingSenderId: '274767761536',
    projectId: 'rent-market-place',
    authDomain: 'rent-market-place.firebaseapp.com',
    storageBucket: 'rent-market-place.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-aAaPQxsIeNFhHkloqftNxGpkhZPQso',
    appId: '1:274767761536:android:b017aec7b2d58a1de45665',
    messagingSenderId: '274767761536',
    projectId: 'rent-market-place',
    storageBucket: 'rent-market-place.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQIT7yufAwUOJtgOixRQE4RkFj36rYiB4',
    appId: '1:274767761536:ios:3c95348940e602abe45665',
    messagingSenderId: '274767761536',
    projectId: 'rent-market-place',
    storageBucket: 'rent-market-place.appspot.com',
    iosClientId: '274767761536-k129tt4bmbmh33b410pos4mth7bbs2v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentMarketPlace',
  );
}
